## Que es Pytorch?

- Es uno de los más populares frameworks de investigación en deep learning.
- Permite la escritura de código rápido de aprendizaje profundo en python.
- Permita el acceso a muchos pre-built modelos de deep learning.

### Por que Pytorch?

- Es código abierto y es usado por diferentes empresas.
- Como se ve en [Code With Papers](https://paperswithcode.com/trends) es el framework más usado en papers.

## Que es un Tensor?

- Son representaciones numérica de objetos o cosas.
- Las redes neuronales toman estas representaciones para realizar las operaciones matemáticas y sacar otra representación de tensor de la probabilidad o categorización que luego son transformados a datos de entendimiento humano.

## Fundamentos de Pytorch

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu118


In [2]:

#* Creando tensores
#* Scalar
scalar = torch.tensor(7) #* Pytorch tensors son creados usando esta función
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item() #* Obtenemos el tensor como un int de python

7

In [5]:

# * Vector
vector = torch.tensor([7, 7])

In [6]:
vector.ndim #* ndim es el numero de brackets en conjunto

1

In [7]:
vector.shape #* shape es el número de elementos 

torch.Size([2])

In [8]:

# * Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:

# * Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 54, 6],
                        [5, 7, 9]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3, 54,  6],
         [ 5,  7,  9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape #* shape es el número de elementos en cada una de las dimensiones del tensor,

torch.Size([1, 3, 3])

In [15]:
TENSOR = torch.tensor([[[[1, 2, 3, 4],
                        [3, 54, 6, 4],
                        [5, 7, 9, 4]]],
                       [[[1, 5, 3, 1],
                        [9, 4, 6, 1],
                        [5, 7, 1, 1]]],
                       [[[1, 5, 3, 1],
                        [9, 4, 6, 1],
                        [5, 7, 1, 1]]]])
print(f'ndim: {TENSOR.ndim}')
print(f'shape: {TENSOR.shape}')

ndim: 4
shape: torch.Size([3, 1, 3, 4])



### Random Tensors 
Random tensors son importantes por la manera en que la redes neuronales aprenden, ya que inician con tensores con datos aleatorios.

In [16]:

#* Create a random tensor of ndim 2
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2319, 0.2569, 0.9197, 0.3473],
        [0.1798, 0.8619, 0.0538, 0.2014],
        [0.6925, 0.8915, 0.9967, 0.6515]])

In [17]:
random_tensor.ndim

2

In [18]:

#* Create a random tensor of ndim 3
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.6051, 0.6441, 0.9753, 0.6950],
         [0.4151, 0.6843, 0.2439, 0.7198],
         [0.9281, 0.7100, 0.5814, 0.9657]]])

In [19]:

#* Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3)) #* height, width, colour channel
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones
Ayudan para la creación de tensores que se inicialicen en cero o unos

In [20]:

#* Create a tensor of all zeros
zeros_tensor = torch.zeros(size=(3,4))
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:

#* Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Creando un rango de tensores y tensors-like

In [23]:

#* Use torch.arange para crear un tensores de rango especifico
one_to_ten = torch.arange(1, 11, 1) #* Start, stop, step
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:

#* Para crear tensores de dimensiones iguales a otros tensores, podemos usar la función torch.zeros_like que crea un tensor de ceros con las dimensiones del tensor de entrada.
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor DataTypes

In [25]:

#* Float 32 tensor es asignado por defecto cuando no se le pasa un dtype
float_32_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=None, #* dtype es el tipo de dato del tensor
                               device=None, #* device es la GPU o CPU
                               requires_grad=False) #* requires_grad es si el tensor requiere gradientes para la optimización
print(f"Tensor: {float_32_tensor}")
print(f"Data type: {float_32_tensor.dtype}")

Tensor: tensor([1., 2., 3.])
Data type: torch.float32


In [26]:
float_16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)
print(f"Tensor: {float_16_tensor}")
print(f"Data type: {float_16_tensor.dtype}")

Tensor: tensor([1., 2., 3.], dtype=torch.float16)
Data type: torch.float16


In [27]:

#* Podemos convertir un tensor a otro tipo de dato
float_16_tensor = float_32_tensor.type(torch.float16)
print(f"Tensor: {float_16_tensor}")
print(f"Data type: {float_16_tensor.dtype}")

Tensor: tensor([1., 2., 3.], dtype=torch.float16)
Data type: torch.float16


para ver que tipos de datos puede aceptar un tensor la puedes ver en esta parte [tipos de dtypes](https://pytorch.org/docs/stable/tensors.html), los distintos tipos especifican la precision computacional.

Precision computacional: https://en.wikipedia.org/wiki/Precision_(computer_science)

**Note**: Tensor datatypes es uno de los 3 grandes errores que se corren con PyTorch y Deep Learning.

Para obtener información sobre los tensores se usa
- Obtener el tipo de dato de un tensor, se puede usar `tensor.dtype`.
- Obtener el shape de un tensor, se puede usar `tensor.shape`.
- Obtener el device de un tensor, se puede usar `tensor.device`.

Los tensores que se crean, se almacenan por defecto en la CPU.



### Manipulando Tensores

En las operaciones de tensores se incluyen:
- Suma
- Resta
- Multiplicación por escalar
- División
- Multiplicaciones de Matriciales

In [28]:

#* Ejemplos
#* Suma
tensor = torch.tensor([1, 2, 3])
tensor + 30

tensor([31, 32, 33])

In [29]:

#* Multiplicación
tensor * 50

tensor([ 50, 100, 150])

In [30]:

# Resta
tensor - 10

tensor([-9, -8, -7])

In [31]:

#* Torch también tiene funciones para operaciones matemáticas
torch.mul(tensor, 10) #* Multiplicación

tensor([10, 20, 30])

Multiplicación de matrices

Hay dos maneras de realizar multiplicaciones en redes neuronales y deep learning:
1. Multiplicación por elemento.
2. Producto punto.

Hay dos reglas principales para realizar la multiplicación de matrices:
1. Las dimensiones internas de cada matrix deben coincidir
   * `(3, 2) @ (3, 2)` no coinciden.
   * `(2, 3) @ (3, 2)` coinciden.
   * `(3, 2) @ (2, 3)` coinciden.
2. La matrix resultado tiene forma de las dimensiones de afuera.
   * `(2, 3) @ (3, 2)` --> `(2,2)`.
   * `(3, 2) @ (2, 3)` --> `(3,3)`.

In [32]:

#* Multiplicación elemento a elemento	
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [33]:

#* Producto Punto
torch.matmul(tensor, tensor)

tensor(14)

In [34]:
import time

In [35]:

#* Tiempo demorado realizando la operación a mano
value = 0
time_start = time.time()
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
time_end = time.time()
print(value)
print(f"Time taken: {time_end - time_start} seconds")

tensor(14)
Time taken: 0.0019986629486083984 seconds


In [36]:
time_start = time.time()
value = torch.matmul(tensor, tensor)
time_end = time.time()
print(value)
print(f"Time taken: {time_end - time_start} seconds")

tensor(14)
Time taken: 0.0 seconds


### Uno de los errores mas comunes en deep learning: errores de shape

In [37]:
# * Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 8], [2, 9], [3, 10]])

tensor_B = torch.tensor([[4, 5], [9, 4], [10, 5]])

#* torch.mm es la misma función que torch.matmul
#! torch.mm(tensor_A, tensor_B)  Error, las dimensiones no son compatibles

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [38]:

#* Para arreglar los problemas de dimension, podemos manipular las dimensiones de los tensores usando transpose.
#* Transpose: intercambia las dimensiones de un tensor.

tensor_B, tensor_B.shape

(tensor([[ 4,  5],
         [ 9,  4],
         [10,  5]]),
 torch.Size([3, 2]))

In [39]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 4,  9, 10],
         [ 5,  4,  5]]),
 torch.Size([2, 3]))

In [40]:
torch.mm(tensor_A, tensor_B.T), torch.mm(tensor_A, tensor_B.T).shape  #* Ahora funciona

(tensor([[44, 41, 50],
         [53, 54, 65],
         [62, 67, 80]]),
 torch.Size([3, 3]))

### Encontrando min, max, mean, sum, etc (Funciones de Agregación en Tensores)

In [41]:
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [42]:

#* min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [43]:

#* max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [44]:

#* mean
#! torch.mean(x), x.mean() #* Error, torch.mean solo funciona con tensores de float
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [45]:

#* sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Encontrando la posición min y max

In [46]:

#* argmin
torch.argmin(x), x.argmin() #* devuelve el índice del valor mínimo

(tensor(0), tensor(0))

In [47]:
x[0]

tensor(1)

In [48]:

#* argmax
torch.argmax(x), x.argmax() #* devuelve el índice del valor máximo

(tensor(9), tensor(9))

In [49]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing y unsqueezing tensor

* Reshaping - cambia la forma o dimensiones de un tensor
* View - retorna una vista de un tensor con ciertas dimensiones pero mantiene la misma memoria como el tensor original.
* Stacking - combina varios tensores de forma horizontal (hstack)  o vertical (vstack).
* Squeezing - remueve todas `1` dimensiones de un tensor.
* Unsquezzing - añade una `1` dimension a un tensor.
* Permute - retorna una vista de un tensor con las dimensiones permutadas de cierta manera.

In [51]:

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [55]:

#* Añadir una dimensión extra
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [56]:

#* Cambiando la vista
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [57]:

#* Si cambiamos algo en z también cambia en x (porque una vista comparte la misma memoria que el tensor original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [58]:

#* Stack tensor encima del otro
x_stacked = torch.stack([x, x, x, x], dim=0) #* dim=0 es el eje vertical
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [59]:
x_stacked = torch.stack([x, x, x, x], dim=1) #* dim=1 es el eje horizontal
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [61]:

#* Squeezing
x_reshaped, x_reshaped.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [65]:
x_squeezed = x_reshaped.squeeze() #* Squeeze elimina las dimensiones de tamaño 1 
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [66]:

#* Unsqueeze
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [70]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0) #* Unsqueeze añade una dimensión de tamaño 1 en la posición especificada
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [71]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [73]:

#* Permute
x_original = torch.rand(size=(224, 224, 3)) #* height, width, colour channel

x_permuted = x_original.permute(2, 0, 1) #* Cambia el orden de las dimensiones 0->1, 1->2, 2->0

print(f"Dimension original: {x_original.shape}")
print(f"Dimension permutada: {x_permuted.shape}") #* Colour channel, height, width

Dimension original: torch.Size([224, 224, 3])
Dimension permutada: torch.Size([3, 224, 224])


### Indexación en Tensores

La indexación es similar a numpy

In [89]:
 
#* Creamos un tensor
x = torch.arange(1., 10.).reshape(1,3,3)
x, x.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.Size([1, 3, 3]))

In [94]:

#* Indexación en la primera dimensión
i = 0
x[i] #* Devuelve el primer elemento del tensor en la primera dimensión

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [99]:

#* Indexación en la segunda dimensión
for j in range(x.shape[1]):
    print(f"Elemento [{i},{j}] en el tensor")
    print(x[0, j]) #* Devuelve el j-ésimo elemento del tensor en la segunda dimensión

Elemento [0,0] en el tensor
tensor([1., 2., 3.])
Elemento [0,1] en el tensor
tensor([4., 5., 6.])
Elemento [0,2] en el tensor
tensor([7., 8., 9.])


In [101]:

#* Indexación en más de dos dimensiones
for j in range(x.shape[1]):
    for k in range(x.shape[2]):
        print(f"Elemento [{i},{j},{k}] en el tensor")
        print(x[0, j, k]) #* Devuelve el k-ésimo elemento del tensor en la k-ésima dimensión 

#* Se sigue la misma lógica para indexar en más dimensiones.

Elemento [0,0,0] en el tensor
tensor(1.)
Elemento [0,0,1] en el tensor
tensor(2.)
Elemento [0,0,2] en el tensor
tensor(3.)
Elemento [0,1,0] en el tensor
tensor(4.)
Elemento [0,1,1] en el tensor
tensor(5.)
Elemento [0,1,2] en el tensor
tensor(6.)
Elemento [0,2,0] en el tensor
tensor(7.)
Elemento [0,2,1] en el tensor
tensor(8.)
Elemento [0,2,2] en el tensor
tensor(9.)


In [104]:

#* Se puede usar : para seleccionar todos los elemetos de una dimensión
x[:, :, 0]

tensor([[1., 4., 7.]])

### Pytorch y Numpy

In [107]:

#* NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #* Convierte un numpy array a un tensor
array, tensor #! Cuando cambiamos el array a tensor, pytorch refleja el tipo por defecto de dato del array

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [109]:

#* Cambiando el valor del array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [110]:

#* Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() #* Convierte un tensor a un numpy array
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [111]:

#* Cambiando el valor del tensor
tensor = tensor + 1
tensor, numpy_tensor #* Cambia el valor del tensor pero no del numpy array

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility

Para reducir la aleatoriedad en una red neuronal PyTorch usa el concepto de **random seed**. Esencialmente random seed lo que hace es darle un "toque" a la aleatoriedad.

In [112]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6612, 0.9407, 0.7683, 0.9052],
        [0.4171, 0.3019, 0.1706, 0.1753],
        [0.2585, 0.0580, 0.7751, 0.4657]])
tensor([[0.5348, 0.4453, 0.6018, 0.5742],
        [0.0116, 0.6891, 0.8377, 0.7784],
        [0.6591, 0.0805, 0.0034, 0.6823]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [115]:

#* Vamos hacer algo random pero con tensores reproducibles
#* Configuramos un random seed
RANDOM_SEED = 23

torch.manual_seed(RANDOM_SEED) #! Funciona con un solo bloque de código
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D) #* Ahora son iguales porque tienen la misma semilla  

tensor([[0.4283, 0.2889, 0.4224, 0.3571],
        [0.9577, 0.1100, 0.2933, 0.9205],
        [0.5876, 0.1299, 0.6729, 0.1028]])
tensor([[0.4283, 0.2889, 0.4224, 0.3571],
        [0.9577, 0.1100, 0.2933, 0.9205],
        [0.5876, 0.1299, 0.6729, 0.1028]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Recurso extra para reproducibilidad:
- [Pytorch Reproducibilidad](https://pytorch.org/docs/stable/notes/randomness.html)
- [Wiki Random Seed](https://en.wikipedia.org/wiki/Random_seed)

### Corriendo tensores y Objetos PyTorch en las GPU's (Cómputos más rápidos)

1. Obteniendo una GPU:
   * Puedes usar Google Colab para usar gpu gratis.
   * Usar tu propia GPU.
   * Usar nubes de computación - GCP, AWS, Azure.

Para las opciones 2,3, se tiene que configurar, para hacer esto, use la documentación de PyTorch: https://pytorch.org/get-started/locally/

In [116]:
!nvidia-smi

Mon Apr 28 16:08:08 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 571.96                 Driver Version: 571.96         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Quadro P2200                 WDDM  |   00000000:01:00.0  On |                  N/A |
| 45%   32C    P8              7W /   75W |    2192MiB /   5120MiB |     18%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

2. Comprobando GPU para PyTorch

Para PyTorch este es capaz de correr en CPU o CPU, para mejor practica esto se puede configurar de la siguiente manera https://pytorch.org/docs/stable/notes/cuda.html#device-agnostic-code

In [117]:
torch.cuda.is_available() #* Verificamos si tenemos una GPU disponible

True

In [118]:

#* Configurando device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu" #* Si hay GPU, usamos GPU, sino CPU
device

'cuda'

In [119]:

#* Contando el numero de devices
torch.cuda.device_count() #* Devuelve el número de GPUs disponibles

1

3. Colocando tensores (y modelos) en la GPU

In [120]:

#* Creando un tensor (Por defecto con la CPU)
tensor = torch.tensor([1, 2, 3])

#* Tensor que no esta en la GPU
print(tensor, tensor.device) #* Devuelve el dispositivo en el que esta el tensor

tensor([1, 2, 3]) cpu


In [121]:

#* Moviendo el tensor a la GPU
tensor_on_gpu = tensor.to(device) #* Movemos el tensor a la GPU
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

4. Moviendo tensores de vuelta a la CPU

In [123]:

#! tensor_on_gpu.numpy() Si el tensor esta en la GPU, no puede transformarse a Numpy
#* Para mover el tensor de la GPU a Numpy, primero debemos configurar el tensor en la CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy() #* Movemos el tensor a la CPU y luego lo convertimos a Numpy
tensor_back_on_cpu

array([1, 2, 3])