## Que es Pytorch?

- Es uno de los más populares frameworks de investigación en deep learning.
- Permite la escritura de código rápido de aprendizaje profundo en python.
- Permita el acceso a muchos pre-built modelos de deep learning.

### Por que Pytorch?

- Es código abierto y es usado por diferentes empresas.
- Como se ve en [Code With Papers](https://paperswithcode.com/trends) es el framework más usado en papers.

## Que es un Tensor?

- Son representaciones numérica de objetos o cosas.
- Las redes neuronales toman estas representaciones para realizar las operaciones matemáticas y sacar otra representación de tensor de la probabilidad o categorización que luego son transformados a datos de entendimiento humano.

## Fundamentos de Pytorch

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu118


In [2]:

#* Creando tensores
#* Scalar
scalar = torch.tensor(7) #* Pytorch tensors son creados usando esta función
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item() #* Obtenemos el tensor como un int de python

7

In [5]:

# * Vector
vector = torch.tensor([7, 7])

In [6]:
vector.ndim #* ndim es el numero de brackets en conjunto

1

In [7]:
vector.shape #* shape es el número de elementos 

torch.Size([2])

In [8]:

# * Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:

# * Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 54, 6],
                        [5, 7, 9]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3, 54,  6],
         [ 5,  7,  9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape #* shape es el número de elementos en cada una de las dimensiones del tensor,

torch.Size([1, 3, 3])

In [15]:
TENSOR = torch.tensor([[[[1, 2, 3, 4],
                        [3, 54, 6, 4],
                        [5, 7, 9, 4]]],
                       [[[1, 5, 3, 1],
                        [9, 4, 6, 1],
                        [5, 7, 1, 1]]],
                       [[[1, 5, 3, 1],
                        [9, 4, 6, 1],
                        [5, 7, 1, 1]]]])
print(f'ndim: {TENSOR.ndim}')
print(f'shape: {TENSOR.shape}')

ndim: 4
shape: torch.Size([3, 1, 3, 4])



### Random Tensors 
Random tensors son importantes por la manera en que la redes neuronales aprenden, ya que inician con tensores con datos aleatorios.

In [16]:

#* Create a random tensor of ndim 2
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3167, 0.9613, 0.7503, 0.8440],
        [0.4884, 0.3292, 0.9541, 0.0218],
        [0.2880, 0.0576, 0.2870, 0.1288]])

In [17]:
random_tensor.ndim

2

In [18]:

#* Create a random tensor of ndim 3
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.6116, 0.5753, 0.0677, 0.5926],
         [0.1201, 0.1361, 0.3514, 0.9668],
         [0.6525, 0.8084, 0.1343, 0.3327]]])

In [19]:

#* Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224,224,3)) #* height, width, colour channel
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones
Ayudan para la creación de tensores que se inicialicen en cero o unos

In [20]:

#* Create a tensor of all zeros
zeros_tensor = torch.zeros(size=(3,4))
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:

#* Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Creando un rango de tensores y tensors-like

In [24]:

#* Use torch.arange para crear un tensores de rango especifico
one_to_ten = torch.arange(1, 11, 1) #* Start, stop, step
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:

#* Para crear tensores de dimensiones iguales a otros tensores, podemos usar la función torch.zeros_like que crea un tensor de ceros con las dimensiones del tensor de entrada.
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor DataTypes

In [31]:

#* Float 32 tensor es asignado por defecto cuando no se le pasa un dtype
float_32_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=None, #* dtype es el tipo de dato del tensor
                               device=None, #* device es la GPU o CPU
                               requires_grad=False) #* requires_grad es si el tensor requiere gradientes para la optimización
print(f"Tensor: {float_32_tensor}")
print(f"Data type: {float_32_tensor.dtype}")

Tensor: tensor([1., 2., 3.])
Data type: torch.float32


In [32]:
float_16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)
print(f"Tensor: {float_16_tensor}")
print(f"Data type: {float_16_tensor.dtype}")

Tensor: tensor([1., 2., 3.], dtype=torch.float16)
Data type: torch.float16


In [33]:

#* Podemos convertir un tensor a otro tipo de dato
float_16_tensor = float_32_tensor.type(torch.float16)
print(f"Tensor: {float_16_tensor}")
print(f"Data type: {float_16_tensor.dtype}")

Tensor: tensor([1., 2., 3.], dtype=torch.float16)
Data type: torch.float16


para ver que tipos de datos puede aceptar un tensor la puedes ver en esta parte [tipos de dtypes](https://pytorch.org/docs/stable/tensors.html), los distintos tipos especifican la precision computacional.

Precision computacional: https://en.wikipedia.org/wiki/Precision_(computer_science)

**Note**: Tensor datatypes es uno de los 3 grandes errores que se corren con PyTorch y Deep Learning.